### PR TITLE
Present users with a creation interface in Website main page

### PR DESCRIPTION
**Pull request by JoeGermuska**
This also includes changes to better support deploying the website and the library to staging servers for preliminary testing.

### CODE REVIEW

**Comment by JoeGermuska** [comment]
Obsoletes #56

**Comment by shortdiv** [comment]
Can we squash some of these commits before merging this into master?

**Comment by JoeGermuska** [comment]
Sure, if you like. It's not a practice I have much experience with. Maybe you can walk me through how you think about it and show me the steps you take. Let me know a good time.

**Comment by shortdiv** [comment]
Sure, let's talk about it this afternoon

**Comment by JoeGermuska** [comment]
OK, I can be stubborn, but in this case, I am accepting defeat. Every step of my attempted rebase had merge conflicts, and I am just not confident that I'm going to keep everything straight correctly.  I resolved the conflict with master, so I think that this is safe to merge.

Thanks for the `rebase` lesson, though. Going forward, I will be more conscientious of keeping an orderly commit history.

**Comment by JoeGermuska** [comment]
@shortdiv in the absence of a methodical rebase/commit cleanup, do you think it would be best to use the "squash and merge" feature? or just tolerate the commit noise and do better in the future?

**Pull request merged**
