### PR TITLE
wip: redrawing line connector

### PR DESCRIPTION
**Pull request by shortdiv**
DO NOT MERGE.

work-in-progress for animating line segment.

### CODE REVIEW

**Comment by shortdiv** [comment]
Basic implementation of line animation. Lmk what you think 

ping @JoeGermuska @zachwise 

line-animate

**Comment by zachwise** [comment]
This is heading in the right direction. I think the animation needs to sync. For example, the fade out of the card should be the same as the line fading out, same for fade in. Line movement should be using the same animation curve and time also.

**Comment by JoeGermuska** [comment]
[Dot/Card connector line animation PR](https://trello.com/c/300MU76R/116-dot-card-connector-line-animation-pr)

**Comment by shortdiv** [comment]
Reworked this, no longer relevant

**Pull request closed without merging**
